### ISSUE TITLE
It would be nice if (some) assertion methods took Functions as well as Strings or Regexes

### ISSUE THREAD

**Issue by wrumsby** [yeoman/yeoman-assert#10]
e.g. say I wanted to assert that the `version` of an installed package meets some criteria by testing it with  something like [semver-compare](https://www.npmjs.com/package/semver-compare) a String or Regex comparison won't work. If I could do something like:

```js
var cmp = require('semver-compare');

...

assert.JSONFileContent('node_modules/eslint/package.json', function (json) {
    return cmp(json.version, '2.2.0');
});
```

that's be nice!

**Comment by SBoudrias** [comment]
Well, you pretty much want to read a json file. No need for assertions method for that. Just `require('my_json_file.json')`

Maybe it'd be nice to have a helper to help read a JSON file to a JS object if the `require` doesn't fit your needs, but that's not related to assertion libraries.
