### ISSUE TITLE
It might be useful to be able to set the base directory in which the assert.file looks

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [yeoman/yeoman-assert#12]
Hi,

I'm creating a yeoman generator that creates a folder and copies all templates into that folder. I would now like to assert that those files are there, but this requires me to append the folder name to all my file asserts. From looking at the code, it seems the directory in which the generator is run is automatically used as the base for `assert.file`. See example below 

``` Javascript
assert.file([
                `${myCreatedFolderPath}/.babelrc`, 
                `${myCreatedFolderPath}/package.json`
            ])
```

Something that might be useful is being able to do something like:

``` Javascript
assert.file([
                `/.babelrc`, 
                `/package.json`
            ], ${myCreatedFolderPath})
```

Please let me know if I'm conceptually missing something here. P.S: I'm happy to get my hands dirty with a pull request.

**Comment by SBoudrias** [comment]
If you're using [yeoman-test](https://github.com/yeoman/yeoman-test), then all paths are going to be relative. That means it's usually safe to skip the full path.

**Comment by marthinus-engelbrecht** [comment]
Relative to what? The directory you are running the generator in?

**Comment by SBoudrias** [comment]
> Relative to what? The directory you are running the generator in?

Yes either `inTmpDir` or `inDir`

**Comment by eddiemonge** [comment]
@marthinus-engelbrecht does that solve your problem?

**Comment by marthinus-engelbrecht** [comment]
I'm not sure. I've actually gone a completely different direction. I've completely forgotten about this.

**Comment by eddiemonge** [comment]
Closing then
