### ISSUE TITLE
Incorrect usage of assert.equals

### ISSUE THREAD

**Issue by kierans** [yeoman/yeoman-assert#13]
In `assert.objectContent` the comparison `assert.equal(content[key], obj[key])` is backwards which leads to incorrect messages when the comparison fails.

**Comment by SBoudrias** [comment]
Send your fix as a PR and we'll merge.

**Comment by kierans** [comment]
Been trying too.  Dodgy internet while travelling.  It's coming. :)

**Comment by kierans** [comment]
@SBoudrias Is there a idea when the next patch version will be released?

**Comment by SBoudrias** [comment]
Right now :)
