### ISSUE TITLE
More flexible assert.fileContent() method

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman-assert#19]
_Initially submitted at https://github.com/yeoman/generator/issues/763 by @gruppjo_

Hi,

I'm often finding myself testing several properties on the same files. For instance:

``` javascript
assert.fileContent([
  ['app/my-module/my-module.js', 'angular.module(\'myModule\','],
  ['app/my-module/my-module.js', '.state(\'my-module\','],
  ['app/my-module/my-module.js', 'url: \'/my-module\',']
]);
```

I'd like to see the `.fileContent(file, reg)` method definition extended so it accepts an array of Regexes or Strings as the second argument as well, thus it's possible to write:

``` javascript
assert.fileContent('app/my-module/my-module.js', [
  'angular.module(\'myModule\',',
  '.state(\'my-module\',',
  'url: \'/my-module\','
]);
```

What do you think?

**Comment by eddiemonge** [comment]
I think this makes the API a bit ambiguous. Does it mean it has to match all of those or any of those? 

Either way, you can accomplish that in pure RegEx. If you can define a sane API that can't be solved with only RegEx, I'll be glad to revisit this.
