### ISSUE TITLE
Does not work with ES6 template strings

### ISSUE THREAD

**Issue by trevordmiller** [yeoman/yeoman-assert#4]
I am using Mocha with the Babel transpiler to write my unit tests for my Yeoman generator. All ES6 syntax is working except for using template strings in place of ES5 string concatenation or Regex (for the second paramater for the `assert.fileContent` method). Being able to use ES6 template strings would be amazing for asserting large file contents, since it respects whitespace in the string:

![yeoman-assert-es6](https://cloud.githubusercontent.com/assets/5497885/9585823/6d478b30-4fd6-11e5-874d-21b95d2ea2a4.png)

**Comment by sindresorhus** [comment]
No, you're just doing it wrong. From looking at the screenshot, you have too many newlines in the template string version. Template strings begin from the backtick, not the next line.

Should be:

```
`.DS_Store
npm-debug.log
node_modules/
`
```

https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=true&spec=false&playground=true&code=%60.DS_Store%0Anpm-debug.log%0Anode_modules%2F%0A%60

-

In the future please use StackOverflow for support questions.

**Comment by trevordmiller** [comment]
I didn't realize it was supported already, sorry. Will do.
